# Generated by Django 3.1 on 2020-08-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenmodel',
            name='image_urls',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='citizenmodel',
            name='images',
            field=models.TextField(null=True),
        ),
    ]
