# Generated by Django 3.1 on 2020-08-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_auto_20200812_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenmodel',
            name='checksum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenmodel',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenmodel',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
