# Generated by Django 3.1 on 2020-08-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0004_auto_20200812_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenmodel',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
